//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emptbl
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Desigination { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<long> ContactNumber { get; set; }
    }
}
